# Generated by Django 4.2.7 on 2025-07-20 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='similarity_score',
            field=models.FloatField(blank=True, help_text='Similarity score for search results', null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='style_description',
            field=models.TextField(blank=True, help_text='Generated player style description'),
        ),
        migrations.AddField(
            model_name='player',
            name='style_embedding',
            field=models.JSONField(blank=True, help_text='Player style embedding vector', null=True),
        ),
    ]
