# Generated by Django 4.2.7 on 2025-07-20 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_similarity_score_player_style_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, help_text='Player last name for sorting', max_length=50, null=True),
        ),
    ]
